version: '3.5'
services:
    db:
        container_name: db_desafio_nodejs
        image: mongo
        command: mongod --quiet --logpath /dev/null
        ports:
            - 27017:27017

    api:
        depends_on:
            - db
        volumes:
            - ./server:/app/server
            - ./server/node_modules:/app/server/node_modules
        container_name: desafio_nodejs
        environment:
            - DATABASE_URL=mongodb://db/desafio_nodejs
        build:
            context: ./server/
        ports:
            - "5000:5000"
        command: yarn start
